# Generated by Django 3.0.7 on 2020-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('Education', 'Education'), ('IT', 'IT'), ('Electronics', 'Electronics'), ('Manufacturing', 'Manufacturing'), ('Health care', 'Health care'), ('finance', 'finance')], max_length=50)),
                ('business', models.CharField(choices=[('enterprise', 'enterprise'), ('collaborator', 'collaborator'), ('investor', 'investor')], max_length=50)),
                ('company', models.TextField()),
            ],
        ),
    ]
